name: Publish StepsTrack to NPM

on:
  push:
    tags:
      - 'v*' # Trigger on version tags
  workflow_dispatch: # Allows manual triggering

jobs:
  # Add a job to trigger and wait for tests to complete
  test:
    uses: ./.github/workflows/test.yml
    
  build-and-publish:
    needs: test  # Wait for tests to complete successfully
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      # Build all packages
      - name: Build
        run: npm run build

      - name: Publish js library to NPM
        run: npm run publish:lib
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
